### ISSUE TITLE
Build fails because of dependancy on stretchr/testify/assert which depends on unsupported errors.Is

### ISSUE THREAD

**Issue by onkarbanerjee** [Shopify/sarama#1947]
##### Versions - Latest version - v1.29.0

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

> # github.com/stretchr/testify/assert
> /root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1704:5: undefined: errors.Is
> /root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1727:6: undefined: errors.Is
> /root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1750:5: undefined: errors.As
> /root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1767:7: undefined: errors.Unwrap
> /root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1771:7: undefined: errors.Unwrap
> note: module requires Go 1.13
> 

##### Problem Description
My app using Sarama v1.29.0 , and am using go.mod. When i am building my app, it seems there is dependancy on `github.com/stretchr/testify/assert` which has dependancy on unsupported apis and i get undefiend error as shown above.

**Comment by dnwe** [comment]
@onkarbanerjee as per the end of your output:

>  note: module requires Go 1.13

https://github.com/Shopify/sarama/blob/master/go.mod#L3

Testify is calling the new errors apis that were [added in Go 1.13](https://golang.org/doc/go1.13#error_wrapping) in 2019 such as [errors.Is](https://pkg.go.dev/errors#Is)

We (Sarama) generally follow Go's official [release policy](https://golang.org/doc/devel/release.html#policy) which is that "Each major Go release is supported until there are two newer major releases". So we only official declare support for Go 1.15 and 1.16 at the moment as those are the two current major releases that are receiving security patches etc.

I imagine that we continue to work with 1.13 and 1.14, but no earlier releases.

I'd strongly recommend upgrading your Go toolchain to at least Go 1.13 if not 1.15/1.16
